version: '3.8'

services:
  mysql:
    image: mysql:8.0
    volumes:
      - ./Database/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: likelion11
      MYSQL_DATABASE: foodfit
    ports:
       - 3307:3306
  nginx:
    build:
      context: .
      dockerfile: ./Frontend/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./Frontend/build:/app/build
      - ./Frontend/nginx.conf:/etc/nginx/conf.d/nginx.conf
    command: nginx -g 'daemon off;'
volumes:
  mysql-data:
